# Agent info
template_root = "fraser_valley_health_authority.index.html"
name = "Fraser Valley Health Authority"
abbreviation = "Health Authority"
jurisdiction_name = "Fraser Valley"
jurisdiction_abbreviation = "FRV"

# Webpage info
title = "Fraser Valley Health Authority"
description = "This is a description"
explanation = "Use the form below to obtain an operating permit."

# Forms:
#
# These structures are used to build the forms
# in the UI.

[[forms]]
name = "operating_permit"
title = "Operating Permit"

  [[forms.hidden]]
  name = "schema"
  value = "operating_permit.fraser_valley_health_authority"

  [[forms.inputs]]
  type = "text"
  required = true
  name = "legal_entity_id"
  pretty = "Legal Entity ID"

  [[forms.inputs]]
  type = "select"
  options = [
    "New Facility",
    "Owner Change",
    "Address Change",
    "Fee Category Change",
    "Services Change",
    "Name Change",
    "Months of Operation Change",
    "Status Change",
    "Permit Corrections"
  ]
  required = true
  name = "application_type"
  pretty = "Application Type"

  [[forms.inputs]]
  type = "date"
  required = true
  name = "effective_date"
  pretty = "Effective Date (yyyy-mm-dd)"

  [[forms.inputs]]
  type = "number"
  required = true
  name = "capacity"
  pretty = "Capacity"

  [[forms.inputs]]
  type = "checkbox"
  required = false
  name = "tobacco"
  pretty = "Tobacco"

  # [[forms.inputs]]
  # type = "select"
  # options = [
  #   "January",
  #   "February",
  #   "March",
  #   "April",
  #   "May",
  #   "June",
  #   "July",
  #   "August",
  #   "September",
  #   "October",
  #   "November",
  #   "December"
  # ]
  # required = true
  # multiple = true
  # name = "months_of_operation"
  # pretty = "Months of Operation"



# Schema mappers:
#
# One for each schema type.
#
# Each mapper is invoked when a request is received
# which contains value "schema" which maps to "for"
# property.

[[schema_mappers]]
for = "operating_permit.fraser_valley_health_authority"

  [[schema_mappers.attributes]]
  name = "legal_entity_id"
  from ="request"
  source = "legal_entity_id"

  [[schema_mappers.attributes]]
  name = "application_type"
  from ="request"
  source = "application_type"

  [[schema_mappers.attributes]]
  name = "effective_date"
  from ="request"
  source = "effective_date"

  [[schema_mappers.attributes]]
  name = "capacity"
  from ="request"
  source = "capacity"

  [[schema_mappers.attributes]]
  name = "tobacco"
  from ="request"
  source = "tobacco"

  # [[schema_mappers.attributes]]
  # name = "months_of_operation"
  # from ="request"
  # source = "months_of_operation"
