# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171016_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voclaim',
            name='claimJSON',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
