# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-31 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171018_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuerservice',
            name='jurisdictionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuerServiceJurisdictions', to='api.Jurisdiction'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permissionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='api.Permission'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='roleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolePermissionRoles', to='api.Role'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='roleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userRoles', to='api.Role'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.User'),
        ),
        migrations.AlterField(
            model_name='verifiedorg',
            name='jurisdictionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifiedOrgJurisdictions', to='api.Jurisdiction'),
        ),
        migrations.AlterField(
            model_name='verifiedorg',
            name='orgTypeId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='verifiedOrgTypes', to='api.VOType'),
        ),
        migrations.AlterField(
            model_name='voclaim',
            name='inactiveClaimReasonId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inactiveClaimReasons', to='api.InactiveClaimReason'),
        ),
        migrations.AlterField(
            model_name='voclaim',
            name='verifiedOrgId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='api.VerifiedOrg'),
        ),
        migrations.AlterField(
            model_name='voclaim',
            name='voClaimType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimTypes', to='api.VOClaimType'),
        ),
        migrations.AlterField(
            model_name='voclaimtype',
            name='issuerOrgId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuerServices', to='api.IssuerService'),
        ),
        migrations.AlterField(
            model_name='vodoingbusinessas',
            name='verifiedOrgId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doingBusinessAs', to='api.VerifiedOrg'),
        ),
        migrations.AlterField(
            model_name='volocation',
            name='verifiedOrgId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.VerifiedOrg'),
        ),
        migrations.AlterField(
            model_name='volocation',
            name='voLocationTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locationTypes', to='api.VOLocationType'),
        ),
    ]
