# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-08 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171031_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoingBusinessAs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CREATE_TIMESTAMP', models.DateTimeField(auto_now_add=True, null=True)),
                ('UPDATE_TIMESTAMP', models.DateTimeField(auto_now=True, null=True)),
                ('dbaName', models.CharField(max_length=255)),
                ('effectiveDate', models.DateField(default=django.utils.timezone.now)),
                ('endDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DOING_BUSINESS_AS',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CREATE_TIMESTAMP', models.DateTimeField(auto_now_add=True, null=True)),
                ('UPDATE_TIMESTAMP', models.DateTimeField(auto_now=True, null=True)),
                ('addressee', models.CharField(blank=True, max_length=255, null=True)),
                ('addlDeliveryInfo', models.CharField(blank=True, max_length=255, null=True)),
                ('unitNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('streetAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('municipality', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('latLong', models.CharField(blank=True, max_length=255, null=True)),
                ('effectiveDate', models.DateField(default=django.utils.timezone.now)),
                ('endDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'LOCATION',
            },
        ),
        migrations.CreateModel(
            name='LocationOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CREATE_TIMESTAMP', models.DateTimeField(auto_now_add=True, null=True)),
                ('UPDATE_TIMESTAMP', models.DateTimeField(auto_now=True, null=True)),
                ('doingBusinessAsId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LocationOrgdoingBusinessAsId', to='api.DoingBusinessAs')),
                ('locationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LocationOrglocationId', to='api.Location')),
            ],
            options={
                'db_table': 'LOCATION_ORG',
            },
        ),
        migrations.CreateModel(
            name='VerifiableClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CREATE_TIMESTAMP', models.DateTimeField(auto_now_add=True, null=True)),
                ('UPDATE_TIMESTAMP', models.DateTimeField(auto_now=True, null=True)),
                ('claimJSON', models.CharField(blank=True, max_length=255, null=True)),
                ('effectiveDate', models.DateField(default=django.utils.timezone.now)),
                ('endDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'VERIFIABLE_CLAIM',
            },
        ),
        migrations.CreateModel(
            name='VerifiableClaimType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CREATE_TIMESTAMP', models.DateTimeField(auto_now_add=True, null=True)),
                ('UPDATE_TIMESTAMP', models.DateTimeField(auto_now=True, null=True)),
                ('claimType', models.CharField(max_length=255)),
                ('base64Logo', models.CharField(blank=True, max_length=255, null=True)),
                ('issuerURL', models.CharField(max_length=255)),
                ('effectiveDate', models.DateField(default=django.utils.timezone.now)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('issuerServiceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuerServices', to='api.IssuerService')),
            ],
            options={
                'db_table': 'VERIFIABLE_CLAIM_TYPE',
            },
        ),
        migrations.CreateModel(
            name='VerifiableOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CREATE_TIMESTAMP', models.DateTimeField(auto_now_add=True, null=True)),
                ('UPDATE_TIMESTAMP', models.DateTimeField(auto_now=True, null=True)),
                ('orgId', models.CharField(max_length=255)),
                ('legalName', models.CharField(max_length=255)),
                ('effectiveDate', models.DateField(default=django.utils.timezone.now)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('jurisdictionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifiableOrgJurisdictions', to='api.Jurisdiction')),
            ],
            options={
                'db_table': 'VERIFIABLE_ORG',
            },
        ),
        migrations.RenameModel(
            old_name='VOLocationType',
            new_name='LocationType',
        ),
        migrations.RenameModel(
            old_name='VOType',
            new_name='VerifiableOrgType',
        ),
        migrations.RemoveField(
            model_name='verifiedorg',
            name='jurisdictionId',
        ),
        migrations.RemoveField(
            model_name='verifiedorg',
            name='orgTypeId',
        ),
        migrations.RemoveField(
            model_name='voclaim',
            name='inactiveClaimReasonId',
        ),
        migrations.RemoveField(
            model_name='voclaim',
            name='verifiedOrgId',
        ),
        migrations.RemoveField(
            model_name='voclaim',
            name='voClaimType',
        ),
        migrations.RemoveField(
            model_name='voclaimtype',
            name='issuerOrgId',
        ),
        migrations.RemoveField(
            model_name='vodoingbusinessas',
            name='verifiedOrgId',
        ),
        migrations.RemoveField(
            model_name='volocation',
            name='verifiedOrgId',
        ),
        migrations.RemoveField(
            model_name='volocation',
            name='voLocationTypeId',
        ),
        migrations.RenameField(
            model_name='locationtype',
            old_name='theType',
            new_name='locType',
        ),
        migrations.RenameField(
            model_name='verifiableorgtype',
            old_name='theType',
            new_name='orgType',
        ),
        migrations.AlterModelTable(
            name='locationtype',
            table='LOCATION_TYPE',
        ),
        migrations.AlterModelTable(
            name='verifiableorgtype',
            table='VERIFIABLE_ORG_TYPE',
        ),
        migrations.DeleteModel(
            name='VerifiedOrg',
        ),
        migrations.DeleteModel(
            name='VOClaim',
        ),
        migrations.DeleteModel(
            name='VOClaimType',
        ),
        migrations.DeleteModel(
            name='VODoingBusinessAs',
        ),
        migrations.DeleteModel(
            name='VOLocation',
        ),
        migrations.AddField(
            model_name='verifiableorg',
            name='orgTypeId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='verifiableOrgTypes', to='api.VerifiableOrgType'),
        ),
        migrations.AddField(
            model_name='verifiableclaim',
            name='claimType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimTypes', to='api.VerifiableClaimType'),
        ),
        migrations.AddField(
            model_name='verifiableclaim',
            name='inactiveClaimReasonId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inactiveClaimReasons', to='api.InactiveClaimReason'),
        ),
        migrations.AddField(
            model_name='verifiableclaim',
            name='verifiableOrgId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='api.VerifiableOrg'),
        ),
        migrations.AddField(
            model_name='locationorg',
            name='verifiableOrgId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LocationOrgverifiableOrgId', to='api.VerifiableOrg'),
        ),
        migrations.AddField(
            model_name='location',
            name='locationTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locationTypes', to='api.LocationType'),
        ),
        migrations.AddField(
            model_name='location',
            name='verifiableOrgId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.VerifiableOrg'),
        ),
        migrations.AddField(
            model_name='doingbusinessas',
            name='verifiableOrgId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doingBusinessAs', to='api.VerifiableOrg'),
        ),
    ]
