# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-10 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171109_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='verifiableOrgId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.VerifiableOrg'),
        ),
    ]
