# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171110_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiableclaim',
            name='claimJSON',
            field=models.TextField(blank=True, null=True),
        ),
    ]
