# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171130_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiableclaimtype',
            name='schemaName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='verifiableclaimtype',
            name='schemaVersion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
