// Implementation Details
// The solr build depends on the solr-base build (more precisely the solr-base image stream)
// which only needs to be rebuilt when there are changes to it's associated repository (https://github.com/bcgov/openshift-solr)
// Therefore, it is unnecessary to build it as part of this pipeline.

// Edit your app's name below
def APP_NAME = 'solr'

// Edit your environment TAG names below
def TAG_NAMES = ['dev', 'test', 'prod']

// Edit your application's context directory here
def CONTEXT_DIRECTORY = 'tob-solr'

// You shouldn't have to edit these if you're following the conventions
def BUILD_CONFIG = APP_NAME
def IMAGESTREAM_NAME = APP_NAME

// Determine whether there were any changes the files within the project's context directory.
@NonCPS
boolean triggerBuild(String contextDirectory) {
  // Determine if code has changed within the source context directory.
  def changeLogSets = currentBuild.changeSets
  def filesChangeCnt = 0
  for (int i = 0; i < changeLogSets.size(); i++) {
    def entries = changeLogSets[i].items
    for (int j = 0; j < entries.length; j++) {
      def entry = entries[j]
      //echo "${entry.commitId} by ${entry.author} on ${new Date(entry.timestamp)}: ${entry.msg}"
      def files = new ArrayList(entry.affectedFiles)
      for (int k = 0; k < files.size(); k++) {
        def file = files[k]
        def filePath = file.path
        //echo ">> ${file.path}"
        if (filePath.contains(contextDirectory)) {
          filesChangeCnt = 1
          k = files.size()
          j = entries.length
        }
      }
    }
  }
  
  if ( filesChangeCnt < 1 ) {
    echo('The changes do not require a build.')
    return false
  }
  else {
    echo('The changes require a build.')
    return true
  } 
}

node {
  if( triggerBuild(CONTEXT_DIRECTORY) ) {    
	// The changeSets contained changes within the project's context directory.
	// Perform a build
	stage('build ' + BUILD_CONFIG) {
      echo "Building: " + BUILD_CONFIG
      openshiftBuild bldCfg: BUILD_CONFIG, showBuildLogs: 'true'
      
      // Don't tag with BUILD_ID so the pruner can do it's job; it won't delete tagged images.
      // Tag the images for deployment based on the image's hash
      IMAGE_HASH = sh (
        script: """oc get istag ${IMAGESTREAM_NAME}:latest -o template --template=\"{{.image.dockerImageReference}}\"|awk -F \":\" \'{print \$3}\'""",
        returnStdout: true).trim()
      echo ">> IMAGE_HASH: ${IMAGE_HASH}"
    }

    stage('deploy-' + TAG_NAMES[0]) {
      openshiftTag destStream: IMAGESTREAM_NAME, verbose: 'true', destTag: TAG_NAMES[0], srcStream: IMAGESTREAM_NAME, srcTag: "${IMAGE_HASH}"
    }
  }
  else {
    // The changeSets did not contain any changes within the project's context directory.
	// Clearly indicate there were no changes.
    stage('No Changes') {
      currentBuild.result = 'SUCCESS'
    }
  }
}